// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "gclust_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// d2_berenhaut_sp_c
Rcpp::NumericVector d2_berenhaut_sp_c(long nv, const Rcpp::IntegerMatrix& el, const Rcpp::NumericMatrix& sp);
RcppExport SEXP gclust_d2_berenhaut_sp_c(SEXP nvSEXP, SEXP elSEXP, SEXP spSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< long >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type el(elSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type sp(spSEXP);
    __result = Rcpp::wrap(d2_berenhaut_sp_c(nv, el, sp));
    return __result;
END_RCPP
}
// d2_berenhaut_c
Rcpp::NumericVector d2_berenhaut_c(long nv, const Rcpp::IntegerMatrix& el);
RcppExport SEXP gclust_d2_berenhaut_c(SEXP nvSEXP, SEXP elSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< long >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type el(elSEXP);
    __result = Rcpp::wrap(d2_berenhaut_c(nv, el));
    return __result;
END_RCPP
}
// all_shortest_paths_c
Rcpp::NumericMatrix all_shortest_paths_c(gclust::index_t nv, const Rcpp::IntegerMatrix& el);
RcppExport SEXP gclust_all_shortest_paths_c(SEXP nvSEXP, SEXP elSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< gclust::index_t >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type el(elSEXP);
    __result = Rcpp::wrap(all_shortest_paths_c(nv, el));
    return __result;
END_RCPP
}
