// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "redwalk_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// dissimilarity_sp_c
Rcpp::NumericVector dissimilarity_sp_c(const redwalk::idx_t nv, const Rcpp::IntegerMatrix& el, const redwalk::MatrixUS& sp);
RcppExport SEXP redwalk_dissimilarity_sp_c(SEXP nvSEXP, SEXP elSEXP, SEXP spSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< const redwalk::idx_t >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type el(elSEXP);
    Rcpp::traits::input_parameter< const redwalk::MatrixUS& >::type sp(spSEXP);
    __result = Rcpp::wrap(dissimilarity_sp_c(nv, el, sp));
    return __result;
END_RCPP
}
// dissimilarity_c
Rcpp::NumericVector dissimilarity_c(const redwalk::idx_t nv, const Rcpp::IntegerMatrix& el);
RcppExport SEXP redwalk_dissimilarity_c(SEXP nvSEXP, SEXP elSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< const redwalk::idx_t >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type el(elSEXP);
    __result = Rcpp::wrap(dissimilarity_c(nv, el));
    return __result;
END_RCPP
}
// dissimilarity_subsets_sp_c
Rcpp::NumericVector dissimilarity_subsets_sp_c(const redwalk::idx_t nv, const Rcpp::IntegerMatrix& el, const Rcpp::IntegerVector& s, const redwalk::MatrixUS& sp);
RcppExport SEXP redwalk_dissimilarity_subsets_sp_c(SEXP nvSEXP, SEXP elSEXP, SEXP sSEXP, SEXP spSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< const redwalk::idx_t >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type el(elSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const redwalk::MatrixUS& >::type sp(spSEXP);
    __result = Rcpp::wrap(dissimilarity_subsets_sp_c(nv, el, s, sp));
    return __result;
END_RCPP
}
// dissimilarity_subsets_c
Rcpp::NumericVector dissimilarity_subsets_c(const redwalk::idx_t nv, const Rcpp::IntegerMatrix& el, const Rcpp::IntegerVector& s);
RcppExport SEXP redwalk_dissimilarity_subsets_c(SEXP nvSEXP, SEXP elSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< const redwalk::idx_t >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type el(elSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type s(sSEXP);
    __result = Rcpp::wrap(dissimilarity_subsets_c(nv, el, s));
    return __result;
END_RCPP
}
