// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "gclust_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// dissimilarity_sp_c
Rcpp::NumericVector dissimilarity_sp_c(long nv, const Rcpp::IntegerMatrix& el, const gclust::MatrixUS& sp);
RcppExport SEXP gclust_dissimilarity_sp_c(SEXP nvSEXP, SEXP elSEXP, SEXP spSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< long >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type el(elSEXP);
    Rcpp::traits::input_parameter< const gclust::MatrixUS& >::type sp(spSEXP);
    __result = Rcpp::wrap(dissimilarity_sp_c(nv, el, sp));
    return __result;
END_RCPP
}
// dissimilarity_c
Rcpp::NumericVector dissimilarity_c(long nv, const Rcpp::IntegerMatrix& el);
RcppExport SEXP gclust_dissimilarity_c(SEXP nvSEXP, SEXP elSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< long >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type el(elSEXP);
    __result = Rcpp::wrap(dissimilarity_c(nv, el));
    return __result;
END_RCPP
}
// dissimilarity_subsets_sp_c
Rcpp::NumericVector dissimilarity_subsets_sp_c(int nv, const Rcpp::IntegerMatrix& el, const Rcpp::IntegerVector& s, const gclust::MatrixUS& sp);
RcppExport SEXP gclust_dissimilarity_subsets_sp_c(SEXP nvSEXP, SEXP elSEXP, SEXP sSEXP, SEXP spSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< int >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type el(elSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const gclust::MatrixUS& >::type sp(spSEXP);
    __result = Rcpp::wrap(dissimilarity_subsets_sp_c(nv, el, s, sp));
    return __result;
END_RCPP
}
// dissimilarity_subsets_c
Rcpp::NumericVector dissimilarity_subsets_c(int nv, const Rcpp::IntegerMatrix& el, const Rcpp::IntegerVector& s);
RcppExport SEXP gclust_dissimilarity_subsets_c(SEXP nvSEXP, SEXP elSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< int >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type el(elSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type s(sSEXP);
    __result = Rcpp::wrap(dissimilarity_subsets_c(nv, el, s));
    return __result;
END_RCPP
}
// check_openmp
void check_openmp();
RcppExport SEXP gclust_check_openmp() {
BEGIN_RCPP
    check_openmp();
    return R_NilValue;
END_RCPP
}
// dostuff_seq
double dostuff_seq(const NumericVector& x);
RcppExport SEXP gclust_dostuff_seq(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    __result = Rcpp::wrap(dostuff_seq(x));
    return __result;
END_RCPP
}
// dostuff_par
double dostuff_par(const NumericVector& x);
RcppExport SEXP gclust_dostuff_par(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    __result = Rcpp::wrap(dostuff_par(x));
    return __result;
END_RCPP
}
// shortest_path_lengths_c
gclust::MatrixUS shortest_path_lengths_c(gclust::index_t nv, const Rcpp::IntegerMatrix& el);
RcppExport SEXP gclust_shortest_path_lengths_c(SEXP nvSEXP, SEXP elSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< gclust::index_t >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type el(elSEXP);
    __result = Rcpp::wrap(shortest_path_lengths_c(nv, el));
    return __result;
END_RCPP
}
// shortest_path_lengths_subsets_c
gclust::MatrixUS shortest_path_lengths_subsets_c(gclust::index_t nv, const Rcpp::IntegerMatrix& el, const Rcpp::IntegerVector& s);
RcppExport SEXP gclust_shortest_path_lengths_subsets_c(SEXP nvSEXP, SEXP elSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< gclust::index_t >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type el(elSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type s(sSEXP);
    __result = Rcpp::wrap(shortest_path_lengths_subsets_c(nv, el, s));
    return __result;
END_RCPP
}
// testFunc
gclust::MatrixUS testFunc(int n);
RcppExport SEXP gclust_testFunc(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(testFunc(n));
    return __result;
END_RCPP
}
