# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dissimilarity_sp_c <- function(nv, el, sp) {
    .Call('gclust_dissimilarity_sp_c', PACKAGE = 'gclust', nv, el, sp)
}

dissimilarity_c <- function(nv, el) {
    .Call('gclust_dissimilarity_c', PACKAGE = 'gclust', nv, el)
}

dissimilarity_subsets_sp_c <- function(nv, el, s, sp) {
    .Call('gclust_dissimilarity_subsets_sp_c', PACKAGE = 'gclust', nv, el, s, sp)
}

dissimilarity_subsets_c <- function(nv, el, s) {
    .Call('gclust_dissimilarity_subsets_c', PACKAGE = 'gclust', nv, el, s)
}

check_openmp <- function() {
    invisible(.Call('gclust_check_openmp', PACKAGE = 'gclust'))
}

dostuff_seq <- function(x) {
    .Call('gclust_dostuff_seq', PACKAGE = 'gclust', x)
}

dostuff_par <- function(x) {
    .Call('gclust_dostuff_par', PACKAGE = 'gclust', x)
}

shortest_path_lengths_c <- function(nv, el) {
    .Call('gclust_shortest_path_lengths_c', PACKAGE = 'gclust', nv, el)
}

shortest_path_lengths_subsets_c <- function(nv, el, s) {
    .Call('gclust_shortest_path_lengths_subsets_c', PACKAGE = 'gclust', nv, el, s)
}

testFunc <- function(n) {
    .Call('gclust_testFunc', PACKAGE = 'gclust', n)
}

