# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

d2_berenhaut_sp_c <- function(nv, el, sp) {
    .Call('gclust_d2_berenhaut_sp_c', PACKAGE = 'gclust', nv, el, sp)
}

d2_berenhaut_c <- function(nv, el) {
    .Call('gclust_d2_berenhaut_c', PACKAGE = 'gclust', nv, el)
}

all_shortest_paths_c <- function(nv, el) {
    .Call('gclust_all_shortest_paths_c', PACKAGE = 'gclust', nv, el)
}

